all: 	\
		bus \
		station-manager \
		comptroller \
		mystation



bus: bus.c
		gcc -Wall -pthread bus.c -o bus

station-manager: station-manager.c
				gcc -Wall -pthread station-manager.c -o station-manager

comptroller: comptroller.c
			gcc -Wall -pthread comptroller.c -o comptroller

mystation: mystation.c
			gcc -Wall -pthread mystation.c -o mystation
